# Generated by Django 4.0.4 on 2022-05-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_telephone_user_filiere_user_matricule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Telephone',
            new_name='phone',
        ),
    ]
