# Generated by Django 4.0.4 on 2022-05-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=10)),
                ('commentaire', models.TextField()),
                ('publish_date', models.DateField()),
                ('status', models.CharField(choices=[('loading', 'En redaction'), ('pending', 'En attente'), ('traitement', 'En traitement'), ('end', 'Terminer')], default='loading', max_length=12)),
                ('asset', models.FileField(blank=True, null=True, upload_to='')),
                ('note1', models.CharField(blank=True, max_length=10, null=True)),
                ('note2', models.CharField(blank=True, max_length=10, null=True)),
                ('examen', models.CharField(blank=True, max_length=10, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_request', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
