# Generated by Django 4.0.4 on 2022-05-27 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('1', 'Rectification de note')], max_length=3)),
                ('commentaire', models.TextField()),
                ('publish_date', models.DateField()),
                ('status', models.CharField(choices=[('loading', 'En redaction'), ('pending', 'En attente'), ('traitement', 'En traitement'), ('end', 'Terminer')], default='loading', max_length=12)),
                ('asset', models.FileField(blank=True, null=True, upload_to='')),
                ('note1', models.CharField(blank=True, max_length=10, null=True)),
                ('note2', models.CharField(blank=True, max_length=10, null=True)),
                ('examen', models.CharField(blank=True, max_length=10, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_request', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('transfert_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to='request.template')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('request_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_comment', to='request.requesthistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
