# Generated by Django 4.0.4 on 2022-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='objet',
            field=models.CharField(choices=[('1', 'Rectification de note')], max_length=3),
        ),
    ]
