# Generated by Django 4.0.4 on 2022-06-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_template_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('loading', 'En redaction'), ('pending', 'En attente'), ('traitement', 'En traitement'), ('end', 'Terminer')], default='loading', max_length=12),
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_image', to='request.template')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
