# Generated by Django 4.0.4 on 2022-05-27 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_requesthistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='transfert_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
