# Generated by Django 4.0.4 on 2022-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_template_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='commentaire',
            field=models.TextField(),
        ),
    ]
