# Generated by Django 4.0.4 on 2022-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_template_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='describe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='existant',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='objet',
            field=models.CharField(max_length=255),
        ),
    ]
