# Generated by Django 4.0.4 on 2022-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_requesthistory_reason_requestimage_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='existant',
            field=models.IntegerField(default=0),
        ),
    ]
