# Generated by Django 4.0.4 on 2022-07-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_template_existant'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
